#pragma once

#ifdef RGB_MATRIX_ENABLE
#	define RGB_MATRIX_KEYPRESSES
#endif

#ifdef RGBLIGHT_HUE_STEP
#	undef RGBLIGHT_HUE_STEP
#endif
#define RGBLIGHT_HUE_STEP 4

#undef ENCODERS_PAD_A
#undef ENCODERS_PAD_B
#define ENCODERS_PAD_A { A4, A15, A9 }
#define ENCODERS_PAD_B { A8, B3, A10 }
#define ENCODER_RESOLUTION 2
